import type { Shape, Rotation } from "../types";

export interface AtlasTile {
  tileId: string;
  shape: Shape;
  rotation: Rotation;
  treasureId: string | null;
  // Pixel bounds in Game_Board_Ref.png (1076×1076)
  x: number;
  y: number;
  w: number;
  h: number;
}

// The reference image is 1076×1076px.
// Tiles are ~150×150px with ~13px gaps, arranged in rows.
// Row start Y values: 30, 196, 362, 528, 694, 860
// Col start X values: 30, 193, 356, 519, 682, 845
// Tile size: 150×150
const T = 150;
const cols = [30, 193, 356, 519, 682, 845];
const rows = [30, 196, 362, 528, 694, 860];

function at(row: number, col: number): { x: number; y: number; w: number; h: number } {
  return { x: cols[col], y: rows[row], w: T, h: T };
}

// Atlas tile layout for treasure identification.
// The 6 movable "t-junction" treasure tiles are:
//   bat, dragon, ghost_bottle, ghost_waving, lady_pig, sorceress
// The 6 movable "corner" treasure tiles are:
//   lizard, moth, owl, scarab, rat, spider
//
// NOTE: The reference image shows these tiles with their icons displayed.
// The tileId corresponds to the IDs generated by generateMovablePool() in constants.ts.

export const ATLAS_TILES: AtlasTile[] = [
  // Row 0
  // [0] Yellow home — fixed, skip for matching
  // [1] Dragon — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_1", shape: "t-junction", rotation: 0, treasureId: "dragon", ...at(0, 1) },
  // [2] Ring — fixed-tile treasure shown on a corner tile. Plain corner in pool.
  { tileId: "movable_corner_0", shape: "corner", rotation: 0, treasureId: null, ...at(0, 2) },
  // [3] blank straight
  { tileId: "movable_straight_0", shape: "straight", rotation: 0, treasureId: null, ...at(0, 3) },
  // [4] Map — fixed-tile treasure shown on straight. Plain straight.
  { tileId: "movable_straight_1", shape: "straight", rotation: 0, treasureId: null, ...at(0, 4) },
  // [5] Sorceress — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_5", shape: "t-junction", rotation: 0, treasureId: "sorceress", ...at(0, 5) },
  // [far right] Red home — fixed, skip

  // Row 1
  // [0] Helmet — fixed-tile treasure on corner. Plain corner.
  { tileId: "movable_corner_1", shape: "corner", rotation: 0, treasureId: null, ...at(1, 0) },
  // [1] Lady Pig — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_4", shape: "t-junction", rotation: 0, treasureId: "lady_pig", ...at(1, 1) },
  // [2] blank corner
  { tileId: "movable_corner_2", shape: "corner", rotation: 0, treasureId: null, ...at(1, 2) },
  // [3] blank straight
  { tileId: "movable_straight_2", shape: "straight", rotation: 0, treasureId: null, ...at(1, 3) },
  // [4] blank straight
  { tileId: "movable_straight_3", shape: "straight", rotation: 0, treasureId: null, ...at(1, 4) },
  // [5] Moth — corner treasure (movable)
  { tileId: "movable_corner_t_1", shape: "corner", rotation: 0, treasureId: "moth", ...at(1, 5) },

  // Row 2
  // [0] Menorah — fixed-tile treasure on corner. Plain corner.
  { tileId: "movable_corner_3", shape: "corner", rotation: 0, treasureId: null, ...at(2, 0) },
  // [1] Bat — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_0", shape: "t-junction", rotation: 0, treasureId: "bat", ...at(2, 1) },
  // [2] Book — fixed-tile treasure on corner. Plain corner.
  { tileId: "movable_corner_4", shape: "corner", rotation: 0, treasureId: null, ...at(2, 2) },
  // [3] blank straight
  { tileId: "movable_straight_4", shape: "straight", rotation: 0, treasureId: null, ...at(2, 3) },
  // [4] Chest/jewel — fixed-tile treasure on corner. Plain corner.
  { tileId: "movable_corner_5", shape: "corner", rotation: 0, treasureId: null, ...at(2, 4) },
  // [5] Spider — corner treasure (movable)
  { tileId: "movable_corner_t_5", shape: "corner", rotation: 0, treasureId: "spider", ...at(2, 5) },

  // Row 3
  // [0] blank corner
  { tileId: "movable_corner_6", shape: "corner", rotation: 0, treasureId: null, ...at(3, 0) },
  // [1] Ghost waving — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_3", shape: "t-junction", rotation: 0, treasureId: "ghost_waving", ...at(3, 1) },
  // [2] blank corner
  { tileId: "movable_corner_7", shape: "corner", rotation: 0, treasureId: null, ...at(3, 2) },
  // [4] Owl — corner treasure (movable)
  { tileId: "movable_corner_t_2", shape: "corner", rotation: 0, treasureId: "owl", ...at(3, 4) },

  // Row 4
  // [0] blank corner
  { tileId: "movable_corner_8", shape: "corner", rotation: 0, treasureId: null, ...at(4, 0) },
  // [1] Ghost bottle — t-junction treasure (movable)
  { tileId: "movable_tjunction_t_2", shape: "t-junction", rotation: 0, treasureId: "ghost_bottle", ...at(4, 1) },
  // [2] Emerald — fixed-tile treasure on straight. Plain straight.
  { tileId: "movable_straight_5", shape: "straight", rotation: 0, treasureId: null, ...at(4, 2) },
  // [3] blank straight
  { tileId: "movable_straight_6", shape: "straight", rotation: 0, treasureId: null, ...at(4, 3) },
  // [4] Keys — fixed-tile treasure on straight. Plain straight.
  { tileId: "movable_straight_7", shape: "straight", rotation: 0, treasureId: null, ...at(4, 4) },
  // [5] Rat — corner treasure (movable)
  { tileId: "movable_corner_t_4", shape: "corner", rotation: 0, treasureId: "rat", ...at(4, 5) },

  // Row 5 (partial)
  // [0] blank straight
  { tileId: "movable_straight_8", shape: "straight", rotation: 0, treasureId: null, ...at(5, 0) },
  // [1] blank straight
  { tileId: "movable_straight_9", shape: "straight", rotation: 0, treasureId: null, ...at(5, 1) },
  // [4] Lizard — corner treasure (movable)
  { tileId: "movable_corner_t_3", shape: "corner", rotation: 0, treasureId: "lizard", ...at(5, 4) },
  // [5] Scarab — corner treasure (movable)
  { tileId: "movable_corner_t_0", shape: "corner", rotation: 0, treasureId: "scarab", ...at(5, 5) },
];

// The spare tile (bottom center of image) — t-junction shape, no treasure
export const ATLAS_SPARE: AtlasTile = {
  tileId: "spare",
  shape: "t-junction",
  rotation: 0,
  treasureId: null,
  x: 463,
  y: 948,
  w: T,
  h: T,
};

// Only the 12 movable treasure tiles matter for template matching.
export const TREASURE_ATLAS_TILES: AtlasTile[] = ATLAS_TILES.filter(
  (t) => t.treasureId !== null
);
